### ISSUE TITLE
Error 500 syncing all Data Elements to GP Staging (staging.dhis.dhmis.org/gp)

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#219]

**Comment by SferaDev** [comment]
```
* INFO  2019-11-15 12:04:36,404 (admin) Updating 2 object(s) of type OptionSet (DefaultObjectBundleService.java [http-nio-8080-exec-5]),
java.lang.NullPointerException,
	at org.hisp.dhis.patch.DefaultPatchService.lambda$calculateMutation$1(DefaultPatchService.java:203),
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193),
	at java.util.Iterator.forEachRemaining(Iterator.java:116),
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801),
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481),
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471),
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708),
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234),
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499),
	at org.hisp.dhis.patch.DefaultPatchService.calculateMutation(DefaultPatchService.java:203),
	at org.hisp.dhis.patch.DefaultPatchService.calculateMutations(DefaultPatchService.java:170),
	at org.hisp.dhis.patch.DefaultPatchService.diff(DefaultPatchService.java:144),
	at org.hisp.dhis.patch.DefaultPatchService.diff(DefaultPatchService.java:99),
	at org.hisp.dhis.dxf2.metadata.objectbundle.DefaultObjectBundleService.handleUpdates(DefaultObjectBundleService.java:362),
	at org.hisp.dhis.dxf2.metadata.objectbundle.DefaultObjectBundleService.commit(DefaultObjectBundleService.java:182),
	at sun.reflect.GeneratedMethodAccessor917.invoke(Unknown Source),
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
	at java.lang.reflect.Method.invoke(Method.java:498),
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333),
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190),
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157),
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99),
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282),
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96),
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179),
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213),
	at com.sun.proxy.$Proxy212.commit(Unknown Source),
	at org.hisp.dhis.dxf2.metadata.DefaultMetadataImportService.importMetadata(DefaultMetadataImportService.java:137),
	at sun.reflect.GeneratedMethodAccessor913.invoke(Unknown Source),
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
	at java.lang.reflect.Method.invoke(Method.java:498),
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333),
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190),
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157),
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99),
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282),
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96),
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179),
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213),
	at com.sun.proxy.$Proxy214.importMetadata(Unknown Source),
	at org.hisp.dhis.webapi.controller.metadata.MetadataImportController.postJsonMetadata(MetadataImportController.java:128),
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
	at java.lang.reflect.Method.invoke(Method.java:498),
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205),
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133),
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97),
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:849),
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:760),
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85),
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967),
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901),
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970),
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872),
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661),
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846),
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742),
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231),
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166),
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52),
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193),
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317),
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127),
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331),
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331),
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331),
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331),
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331),
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331),
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:215),
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331),
	at org.hisp.dhis.security.filter.CorsFilter.doFilter(CorsFilter.java:126),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331),
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331),
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331),
	at org.hisp.dhis.security.filter.CustomAuthenticationFilter.doFilter(CustomAuthenticationFilter.java:69),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331),
	at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:176),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331),
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331),
	at org.hisp.dhis.security.filter.AutomaticAccessFilter.doFilter(AutomaticAccessFilter.java:115),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331),
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66),
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331),
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56),
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331),
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105),
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331),
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214),
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177),
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347),
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263),
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193),
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166),
	at org.hisp.dhis.servlet.filter.HttpUrlPatternFilter.doFilter(HttpUrlPatternFilter.java:120),
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193),
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166),
	at org.springframework.web.filter.ShallowEtagHeaderFilter.doFilterInternal(ShallowEtagHeaderFilter.java:110),
	at org.hisp.dhis.servlet.filter.ExcludableShallowEtagHeaderFilter.doFilterInternal(ExcludableShallowEtagHeaderFilter.java:112),
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107),
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193),
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166),
	at org.springframework.orm.hibernate5.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151),
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107),
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193),
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166),
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197),
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107),
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193),
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166),
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197),
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107),
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347),
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263),
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193),
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166),
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198),
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96),
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493),
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140),
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81),
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650),
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87),
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342),
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800),
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66),
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806),
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498),
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49),
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149),
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624),
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61),
	at java.lang.Thread.run(Thread.java:748),
* WARN  2019-11-15 12:04:36,810 Resolved [java.lang.NullPointerException] (AbstractHandlerExceptionResolver.java [http-nio-8080-exec-5]),
```

**Comment by adrianq** [comment]
This has to do with option sets. Currently, we have identified two data  elements that  have option set.
One of them failing-> DE: DDC Capturing Done This Month Option Set: DDC Capturing Done This Month
One of them is working-> DE: Level at which data capturing was done this month  Option Set: Data Capturing Level
Java Error Server side is pointing to this line  https://github.com/dhis2/dhis2-core/blob/2.30/dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/patch/DefaultPatchService.java#L202
