### ISSUE TITLE
Intermitent error 500 during program metadata sync

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/metadata-synchronization#482]
```
  Running:  manual-metadata-sync.spec.js                                                  (11 of 14)
  Manual metadata sync
    Data element
      ✓ should have the correct title (5480ms)
      ✓ should sync correctly one data element (20288ms)
      ✓ should show the instance selection step error if user try click on next without selecting an instance (11125ms)
      ✓ should have synchronize button disabled to open sync dialog (8112ms)
      ✓ should have synchronize button disabled if only contains default include exclude (9382ms)
      ✓ should have synchronize button enabled if contains org unit, periods, category options and one instance (10635ms)
      ✓ should sync correctly with dependencies with default include rule (16801ms)
      ✓ should sync correctly without excluded dependencies if rules are customized (22227ms)
    Dashboard
      ✓ should sync correctly one dashboard (14875ms)
    User group
      ✓ should sync correctly one user group (14650ms)
    Data set
      ✓ should sync correctly one data set (17852ms)
    Program
      1) should sync correctly one program
  11 passing (4m)
  1 failing
  1) Manual metadata sync
       Program
         should sync correctly one program:
     CypressError: Timed out retrying: Expected to find content: 'Success' within the element: [ <p.MuiTypography-root.makeStyles-expansionPanelHeading1-3769.MuiTypography-body1>, 3 more... ] but never did.
      at cypressErr (http://localhost:8081/__cypress/runner/cypress_runner.js:138644:9)
      at throwErr (http://localhost:8081/__cypress/runner/cypress_runner.js:138577:11)
      at Object.throwErrByPath (http://localhost:8081/__cypress/runner/cypress_runner.js:138625:3)
      at retry (http://localhost:8081/__cypress/runner/cypress_runner.js:132905:19)
      at onFailFn (http://localhost:8081/__cypress/runner/cypress_runner.js:121122:16)
      at tryCatcher (http://localhost:8081/__cypress/runner/cypress_runner.js:165465:23)
      at Promise._settlePromiseFromHandler (http://localhost:8081/__cypress/runner/cypress_runner.js:163401:31)
      at Promise._settlePromise (http://localhost:8081/__cypress/runner/cypress_runner.js:163458:18)
      at Promise._settlePromise0 (http://localhost:8081/__cypress/runner/cypress_runner.js:163503:10)
      at Promise._settlePromises (http://localhost:8081/__cypress/runner/cypress_runner.js:163578:18)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://localhost:8081/__cypress/runner/cypress_runner.js:160190:16)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:8081/__cypress/runner/cypress_runner.js:160200:10)
      at Async.drainQueues (http://localhost:8081/__cypress/runner/cypress_runner.js:160074:14)
```

**Comment by adrianq** [comment]
I think we can close this as it may have to do with a server error. Correct me if I am wrong and you prefer to keep it open @SferaDev
